inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'app/views/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 12

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false