inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'app/views/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Enable: true
  Exclude:
    - spec/**/*

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false