services:
  web:
    image: mame-zefu-web:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "./bin/dev"
    tty: true
    volumes:
      - .:/rails
      - cache:/rails/tmp/cache
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
  postgres:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mame_zefu_development
      - POSTGRES_USER=mame_zefu
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mame_zefu -d mame_zefu_development"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
volumes:
  cache:
  pgdata:
