# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.3.7
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
        curl \
        libjemalloc2 \
        libvips \
        libpq-dev \
        python3 \
        python3-venv \
        python3-pip && \
    apt-get install --no-install-recommends -y \
        build-essential \
        curl \
        git \
        pkg-config \
        libyaml-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY requirements.txt /rails/requirements.txt
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir -r /rails/requirements.txt

ENV PATH="/opt/venv/bin:$PATH"

ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
