name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    uses: ./.github/workflows/rails-docker-ci.yml
    with:
      job_type: test
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    uses: ./.github/workflows/rails-docker-ci.yml
    with:
      job_type: lint
